myproject/urls.py
# urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from GolfApp import views
from GolfApp.views import ParticipantCreateView
from GolfApp.views import ParticipantUpdateView


urlpatterns = [
    path('', views.index, name='index'),
    path('group_results/', views.group_results, name='group_results'),
    path('register/', views.ParticipantCreateView.as_view(), name='participant_register'),
    path('delete/', views.show_delete_participants_form, name='show_delete_participants_form'),
    path('delete_participants/', views.delete_participants, name='delete_participants'),
    path('participant/edit/<int:pk>/', ParticipantUpdateView.as_view(), name='participant_edit'),

]  # 他のURLパターン...

GolfApp/models.py
from django.db import models

class Participant(models.Model):
    name = models.CharField(max_length=100)
    average_score = models.IntegerField(default=0)  # FloatFieldからIntegerFieldに変更
    gender = models.CharField(max_length=1, choices=(('M', '男'), ('F', '女')))
    is_etiquette_leader = models.BooleanField(default=False)

GolfApp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from .grouping import group_participants
from .models import Participant
from django.contrib import messages  # メッセージフレームワークをインポート
from django.shortcuts import render
from django.views.generic.edit import UpdateView


class ParticipantCreateView(CreateView):
    model = Participant
    fields = ['name', 'average_score', 'gender', 'is_etiquette_leader']
    template_name = 'participant_form.html'
    success_url = reverse_lazy('index')  # 登録後にトップページにリダイレクト

def index(request):
    if request.method == 'POST':
        selected_ids = request.POST.getlist('participants[]')
        print("選択された参加者ID:", selected_ids)
        selected_participants = Participant.objects.filter(id__in=selected_ids)
        if len(selected_participants) < 3:
            needed_participants = 3 - len(selected_participants)
            messages.error(request, f'参加者が足りません。あと{needed_participants}名の参加者が必要です。')
            return redirect('index')

        # 選択された参加者のみをグループ分けする
        groups = group_participants(list(selected_participants))
        print(selected_participants)
        if any(len(group) < 3 for group in groups):
            messages.error(request, 'グループ分けに失敗しました。各グループは3名以上でなければなりません。')
            return redirect('index')
        
        # グループ分けの結果をセッションに保存
        request.session['groups'] = [[participant.id for participant in group] for group in groups]
        
        return redirect('group_results')
    else:
        participants = Participant.objects.all()
        return render(request, 'index.html', {'participants': participants})
def group_results(request):
    # セッションからグループIDのリストを取得
    group_ids = request.session.get('groups', [])
    
    # 取得したグループIDのリストをコンソールに出力
    print("取得したグループIDのリスト:", group_ids)
    
    # グループIDから参加者オブジェクトのリストを再構築
    groups = [Participant.objects.filter(id__in=group) for group in group_ids]
    
    # 再構築したグループのリストをコンソールに出力
    print("再構築したグループのリスト:")
    for i, group in enumerate(groups, start=1):
        print(f"グループ {i}: {[participant.name for participant in group]}")
    
    return render(request, 'group_results.html', {'groups': groups})

def delete_participants(request):
    if request.method == 'POST':
        selected_ids = request.POST.getlist('delete_participants[]')
        Participant.objects.filter(id__in=selected_ids).delete()
        messages.success(request, '選択された参加者を削除しました。')
    return redirect('index')

def show_delete_participants_form(request):
    participants = Participant.objects.all()
    return render(request, 'delete_participants.html', {'participants': participants})

class ParticipantUpdateView(UpdateView):
    model = Participant
    fields = ['name', 'average_score', 'gender', 'is_etiquette_leader']
    template_name = 'participant_edit_form.html'
    success_url = reverse_lazy('index')  # 編集後にトップページにリダイレクト

GolfApp/templates/delete_participants.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>参加者削除</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>参加者削除</h1>
    <form action="{% url 'delete_participants' %}" method="post">
        {% csrf_token %}
        {% for participant in participants %}
        <div>
            <input type="checkbox" id="delete_participant{{ participant.id }}" name="delete_participants[]" value="{{ participant.id }}">
            <label for="delete_participant{{ participant.id }}">{{ participant.name }}</label>
        </div>
        {% endfor %}
        <button type="submit">選択した参加者を削除</button>
    </form>
    <a href="{% url 'index' %}">戻る</a>
</body>
</html>

GolfApp/templates/group_results.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>グループ分け結果</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>グループ分け結果</h1>
    {% for group in groups %}
        <h2>グループ {{ forloop.counter }}</h2>
        <ul>
            {% for participant in group %}
                <li>{{ participant.name }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
    <a href="{% url 'index' %}">戻る</a>
</body>
</html>

GolfApp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>ゴルフコンペ参加者一覧</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>ゴルフコンペ参加者一覧</h1>

    <!-- 全選択・選択解除ボタンの追加 -->
    <div>
        <button type="button" id="selectAll">すべて選択</button>
        <button type="button" id="deselectAll">選択を解除</button>
    </div>
    <div id="selectedCount">選択された参加者の人数: 0</div>
    <form action="{% url 'index' %}" method="post">
        {% csrf_token %}
        <table class="participant-list">
            <thead>
                <tr>
                    <th></th> <!-- チェックボックス用のヘッダー -->
                    <th>名前</th>
                    <th>性別</th>
                    <th>平均スコア</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for participant in participants %}
                <tr>
                    <td><input type="checkbox" name="participants[]" value="{{ participant.id }}"></td>
                    <td>{{ participant.name }}{% if participant.is_etiquette_leader %}⛳️{% endif %}</td>
                    <td>{% if participant.gender == 'M' %}男性{% elif participant.gender == 'F' %}女性{% else %}その他{% endif %}</td>
                    <td>{{ participant.average_score }}</td>
                    <td>
                        <!-- 編集ページへのリンクを含む「編集」ボタン -->
                        <a href="{% url 'participant_edit' participant.id %}" class="btn btn-primary">編集</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">グループ分け実行</button>
        <div>
            <a href="{% url 'participant_register' %}" class="btn btn-primary">参加者登録</a>
            <a href="{% url 'show_delete_participants_form' %}" class="btn btn-primary">参加者の削除</a>
        </div>
    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const updateSelectedCount = () => {
                const selectedCount = document.querySelectorAll('input[type="checkbox"][name="participants[]"]:checked').length;
                document.getElementById('selectedCount').textContent = `選択された参加者の人数: ${selectedCount}`;
            };
        
            // すべて選択・選択解除ボタンのイベントリスナーに人数更新機能を追加
            document.getElementById('selectAll').addEventListener('click', function() {
                document.querySelectorAll('input[type="checkbox"][name="participants[]"]').forEach(function(checkbox) {
                    checkbox.checked = true;
                });
                updateSelectedCount(); // 人数を更新
            });
        
            document.getElementById('deselectAll').addEventListener('click', function() {
                document.querySelectorAll('input[type="checkbox"][name="participants[]"]').forEach(function(checkbox) {
                    checkbox.checked = false;
                });
                updateSelectedCount(); // 人数を更新
            });
        
            // 各チェックボックスの状態変更時に人数を更新
            document.querySelectorAll('input[type="checkbox"][name="participants[]"]').forEach(function(checkbox) {
                checkbox.addEventListener('change', updateSelectedCount);
            });
        
            // 初期状態での人数更新
            updateSelectedCount();
        });
        </script>
</body>
</html>

GolfApp/templates/participant_edit_form.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>参加者編集</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>参加者編集</h1>
    <form method="post">
        {% csrf_token %}        
        <!-- フォームフィールドを個別にレンダリング -->
        <p>
            <label for="id_name">名前:</label>
            {{ form.name }}
        </p>
        <p>
            <label for="id_score">スコア:</label>
            {{ form.average_score }}
        </p>
        <p>
            <label for="id_gender">性別:</label>
            {{ form.gender }}
        </p>
        <p>
            <label for="id_is_etiquette_leader">エチケットリーダー:</label>
            {{ form.is_etiquette_leader }}
        </p>

        <button type="submit">更新</button>
    </form>
    <a href="{% url 'index' %}">戻る</a>
</body>
</html>

GolfApp/templates/participant_form.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>参加者登録</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <h1>参加者登録</h1>
    <form method="post">
        {% csrf_token %}
        <!-- フォームフィールドを個別にレンダリング -->
        <p>
            <label for="id_name">名前:</label>
            {{ form.name }}
        </p>
        <p>
            <label for="id_score">スコア:</label>
            {{ form.average_score }}
        </p>
        <p>
            <label for="id_gender">性別:</label>
            {{ form.gender }}
        </p>
        <p>
            <label for="id_is_etiquette_leader">エチケットリーダー:</label>
            {{ form.is_etiquette_leader }}
        </p>
        <button type="submit">登録</button>
    </form>
</body>
</html>